// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: ZScanProto.proto

package zscanproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZPiController_SetLEDStatus_FullMethodName     = "/zscanproto.ZPiController/SetLEDStatus"
	ZPiController_GetLED_FullMethodName           = "/zscanproto.ZPiController/GetLED"
	ZPiController_ConfigureToF_FullMethodName     = "/zscanproto.ZPiController/ConfigureToF"
	ZPiController_EnableToF_FullMethodName        = "/zscanproto.ZPiController/EnableToF"
	ZPiController_DisableToF_FullMethodName       = "/zscanproto.ZPiController/DisableToF"
	ZPiController_ActivateToF_FullMethodName      = "/zscanproto.ZPiController/ActivateToF"
	ZPiController_DeactivateToF_FullMethodName    = "/zscanproto.ZPiController/DeactivateToF"
	ZPiController_InitCamera_FullMethodName       = "/zscanproto.ZPiController/InitCamera"
	ZPiController_CleanupCamera_FullMethodName    = "/zscanproto.ZPiController/CleanupCamera"
	ZPiController_ActivateCamera_FullMethodName   = "/zscanproto.ZPiController/ActivateCamera"
	ZPiController_DeactivateCamera_FullMethodName = "/zscanproto.ZPiController/DeactivateCamera"
	ZPiController_ConfigureCamera_FullMethodName  = "/zscanproto.ZPiController/ConfigureCamera"
)

// ZPiControllerClient is the client API for ZPiController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZPiControllerClient interface {
	SetLEDStatus(ctx context.Context, in *LEDStatusRequest, opts ...grpc.CallOption) (*Status, error)
	GetLED(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LEDState, error)
	ConfigureToF(ctx context.Context, in *ToFConfig, opts ...grpc.CallOption) (*Status, error)
	EnableToF(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error)
	DisableToF(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error)
	ActivateToF(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error)
	DeactivateToF(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error)
	InitCamera(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error)
	CleanupCamera(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error)
	ActivateCamera(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error)
	DeactivateCamera(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error)
	ConfigureCamera(ctx context.Context, in *CameraConfig, opts ...grpc.CallOption) (*Status, error)
}

type zPiControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewZPiControllerClient(cc grpc.ClientConnInterface) ZPiControllerClient {
	return &zPiControllerClient{cc}
}

func (c *zPiControllerClient) SetLEDStatus(ctx context.Context, in *LEDStatusRequest, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, ZPiController_SetLEDStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zPiControllerClient) GetLED(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LEDState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LEDState)
	err := c.cc.Invoke(ctx, ZPiController_GetLED_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zPiControllerClient) ConfigureToF(ctx context.Context, in *ToFConfig, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, ZPiController_ConfigureToF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zPiControllerClient) EnableToF(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, ZPiController_EnableToF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zPiControllerClient) DisableToF(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, ZPiController_DisableToF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zPiControllerClient) ActivateToF(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, ZPiController_ActivateToF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zPiControllerClient) DeactivateToF(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, ZPiController_DeactivateToF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zPiControllerClient) InitCamera(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, ZPiController_InitCamera_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zPiControllerClient) CleanupCamera(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, ZPiController_CleanupCamera_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zPiControllerClient) ActivateCamera(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, ZPiController_ActivateCamera_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zPiControllerClient) DeactivateCamera(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, ZPiController_DeactivateCamera_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zPiControllerClient) ConfigureCamera(ctx context.Context, in *CameraConfig, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, ZPiController_ConfigureCamera_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZPiControllerServer is the server API for ZPiController service.
// All implementations must embed UnimplementedZPiControllerServer
// for forward compatibility.
type ZPiControllerServer interface {
	SetLEDStatus(context.Context, *LEDStatusRequest) (*Status, error)
	GetLED(context.Context, *Empty) (*LEDState, error)
	ConfigureToF(context.Context, *ToFConfig) (*Status, error)
	EnableToF(context.Context, *Empty) (*Status, error)
	DisableToF(context.Context, *Empty) (*Status, error)
	ActivateToF(context.Context, *Empty) (*Status, error)
	DeactivateToF(context.Context, *Empty) (*Status, error)
	InitCamera(context.Context, *Empty) (*Status, error)
	CleanupCamera(context.Context, *Empty) (*Status, error)
	ActivateCamera(context.Context, *Empty) (*Status, error)
	DeactivateCamera(context.Context, *Empty) (*Status, error)
	ConfigureCamera(context.Context, *CameraConfig) (*Status, error)
	mustEmbedUnimplementedZPiControllerServer()
}

// UnimplementedZPiControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZPiControllerServer struct{}

func (UnimplementedZPiControllerServer) SetLEDStatus(context.Context, *LEDStatusRequest) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLEDStatus not implemented")
}
func (UnimplementedZPiControllerServer) GetLED(context.Context, *Empty) (*LEDState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLED not implemented")
}
func (UnimplementedZPiControllerServer) ConfigureToF(context.Context, *ToFConfig) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureToF not implemented")
}
func (UnimplementedZPiControllerServer) EnableToF(context.Context, *Empty) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableToF not implemented")
}
func (UnimplementedZPiControllerServer) DisableToF(context.Context, *Empty) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableToF not implemented")
}
func (UnimplementedZPiControllerServer) ActivateToF(context.Context, *Empty) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateToF not implemented")
}
func (UnimplementedZPiControllerServer) DeactivateToF(context.Context, *Empty) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivateToF not implemented")
}
func (UnimplementedZPiControllerServer) InitCamera(context.Context, *Empty) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method InitCamera not implemented")
}
func (UnimplementedZPiControllerServer) CleanupCamera(context.Context, *Empty) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanupCamera not implemented")
}
func (UnimplementedZPiControllerServer) ActivateCamera(context.Context, *Empty) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateCamera not implemented")
}
func (UnimplementedZPiControllerServer) DeactivateCamera(context.Context, *Empty) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivateCamera not implemented")
}
func (UnimplementedZPiControllerServer) ConfigureCamera(context.Context, *CameraConfig) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureCamera not implemented")
}
func (UnimplementedZPiControllerServer) mustEmbedUnimplementedZPiControllerServer() {}
func (UnimplementedZPiControllerServer) testEmbeddedByValue()                       {}

// UnsafeZPiControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZPiControllerServer will
// result in compilation errors.
type UnsafeZPiControllerServer interface {
	mustEmbedUnimplementedZPiControllerServer()
}

func RegisterZPiControllerServer(s grpc.ServiceRegistrar, srv ZPiControllerServer) {
	// If the following call panics, it indicates UnimplementedZPiControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZPiController_ServiceDesc, srv)
}

func _ZPiController_SetLEDStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LEDStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZPiControllerServer).SetLEDStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZPiController_SetLEDStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZPiControllerServer).SetLEDStatus(ctx, req.(*LEDStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZPiController_GetLED_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZPiControllerServer).GetLED(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZPiController_GetLED_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZPiControllerServer).GetLED(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZPiController_ConfigureToF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToFConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZPiControllerServer).ConfigureToF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZPiController_ConfigureToF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZPiControllerServer).ConfigureToF(ctx, req.(*ToFConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZPiController_EnableToF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZPiControllerServer).EnableToF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZPiController_EnableToF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZPiControllerServer).EnableToF(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZPiController_DisableToF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZPiControllerServer).DisableToF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZPiController_DisableToF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZPiControllerServer).DisableToF(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZPiController_ActivateToF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZPiControllerServer).ActivateToF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZPiController_ActivateToF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZPiControllerServer).ActivateToF(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZPiController_DeactivateToF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZPiControllerServer).DeactivateToF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZPiController_DeactivateToF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZPiControllerServer).DeactivateToF(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZPiController_InitCamera_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZPiControllerServer).InitCamera(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZPiController_InitCamera_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZPiControllerServer).InitCamera(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZPiController_CleanupCamera_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZPiControllerServer).CleanupCamera(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZPiController_CleanupCamera_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZPiControllerServer).CleanupCamera(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZPiController_ActivateCamera_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZPiControllerServer).ActivateCamera(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZPiController_ActivateCamera_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZPiControllerServer).ActivateCamera(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZPiController_DeactivateCamera_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZPiControllerServer).DeactivateCamera(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZPiController_DeactivateCamera_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZPiControllerServer).DeactivateCamera(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZPiController_ConfigureCamera_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CameraConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZPiControllerServer).ConfigureCamera(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZPiController_ConfigureCamera_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZPiControllerServer).ConfigureCamera(ctx, req.(*CameraConfig))
	}
	return interceptor(ctx, in, info, handler)
}

// ZPiController_ServiceDesc is the grpc.ServiceDesc for ZPiController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZPiController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zscanproto.ZPiController",
	HandlerType: (*ZPiControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetLEDStatus",
			Handler:    _ZPiController_SetLEDStatus_Handler,
		},
		{
			MethodName: "GetLED",
			Handler:    _ZPiController_GetLED_Handler,
		},
		{
			MethodName: "ConfigureToF",
			Handler:    _ZPiController_ConfigureToF_Handler,
		},
		{
			MethodName: "EnableToF",
			Handler:    _ZPiController_EnableToF_Handler,
		},
		{
			MethodName: "DisableToF",
			Handler:    _ZPiController_DisableToF_Handler,
		},
		{
			MethodName: "ActivateToF",
			Handler:    _ZPiController_ActivateToF_Handler,
		},
		{
			MethodName: "DeactivateToF",
			Handler:    _ZPiController_DeactivateToF_Handler,
		},
		{
			MethodName: "InitCamera",
			Handler:    _ZPiController_InitCamera_Handler,
		},
		{
			MethodName: "CleanupCamera",
			Handler:    _ZPiController_CleanupCamera_Handler,
		},
		{
			MethodName: "ActivateCamera",
			Handler:    _ZPiController_ActivateCamera_Handler,
		},
		{
			MethodName: "DeactivateCamera",
			Handler:    _ZPiController_DeactivateCamera_Handler,
		},
		{
			MethodName: "ConfigureCamera",
			Handler:    _ZPiController_ConfigureCamera_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ZScanProto.proto",
}
