// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ZScanProto.proto

package zscanproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LEDStatus int32

const (
	LEDStatus_VOID    LEDStatus = 0
	LEDStatus_SUCCESS LEDStatus = 1
	LEDStatus_PENDING LEDStatus = 2
	LEDStatus_FAILED  LEDStatus = 3
)

// Enum value maps for LEDStatus.
var (
	LEDStatus_name = map[int32]string{
		0: "VOID",
		1: "SUCCESS",
		2: "PENDING",
		3: "FAILED",
	}
	LEDStatus_value = map[string]int32{
		"VOID":    0,
		"SUCCESS": 1,
		"PENDING": 2,
		"FAILED":  3,
	}
)

func (x LEDStatus) Enum() *LEDStatus {
	p := new(LEDStatus)
	*p = x
	return p
}

func (x LEDStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LEDStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ZScanProto_proto_enumTypes[0].Descriptor()
}

func (LEDStatus) Type() protoreflect.EnumType {
	return &file_ZScanProto_proto_enumTypes[0]
}

func (x LEDStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LEDStatus.Descriptor instead.
func (LEDStatus) EnumDescriptor() ([]byte, []int) {
	return file_ZScanProto_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_ZScanProto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_ZScanProto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_ZScanProto_proto_rawDescGZIP(), []int{0}
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_ZScanProto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_ZScanProto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_ZScanProto_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LEDStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        LEDStatus              `protobuf:"varint,1,opt,name=status,proto3,enum=zscanproto.LEDStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LEDStatusRequest) Reset() {
	*x = LEDStatusRequest{}
	mi := &file_ZScanProto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LEDStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LEDStatusRequest) ProtoMessage() {}

func (x *LEDStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ZScanProto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LEDStatusRequest.ProtoReflect.Descriptor instead.
func (*LEDStatusRequest) Descriptor() ([]byte, []int) {
	return file_ZScanProto_proto_rawDescGZIP(), []int{2}
}

func (x *LEDStatusRequest) GetStatus() LEDStatus {
	if x != nil {
		return x.Status
	}
	return LEDStatus_VOID
}

type LEDState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Red           uint32                 `protobuf:"varint,1,opt,name=red,proto3" json:"red,omitempty"`
	Green         uint32                 `protobuf:"varint,2,opt,name=green,proto3" json:"green,omitempty"`
	Blue          uint32                 `protobuf:"varint,3,opt,name=blue,proto3" json:"blue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LEDState) Reset() {
	*x = LEDState{}
	mi := &file_ZScanProto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LEDState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LEDState) ProtoMessage() {}

func (x *LEDState) ProtoReflect() protoreflect.Message {
	mi := &file_ZScanProto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LEDState.ProtoReflect.Descriptor instead.
func (*LEDState) Descriptor() ([]byte, []int) {
	return file_ZScanProto_proto_rawDescGZIP(), []int{3}
}

func (x *LEDState) GetRed() uint32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *LEDState) GetGreen() uint32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *LEDState) GetBlue() uint32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

var File_ZScanProto_proto protoreflect.FileDescriptor

const file_ZScanProto_proto_rawDesc = "" +
	"\n" +
	"\x10ZScanProto.proto\x12\n" +
	"zscanproto\"\a\n" +
	"\x05Empty\"<\n" +
	"\x06Status\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\x10LEDStatusRequest\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.zscanproto.LEDStatusR\x06status\"F\n" +
	"\bLEDState\x12\x10\n" +
	"\x03red\x18\x01 \x01(\rR\x03red\x12\x14\n" +
	"\x05green\x18\x02 \x01(\rR\x05green\x12\x12\n" +
	"\x04blue\x18\x03 \x01(\rR\x04blue*;\n" +
	"\tLEDStatus\x12\b\n" +
	"\x04VOID\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\v\n" +
	"\aPENDING\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x032\x84\x01\n" +
	"\rZPiController\x12@\n" +
	"\fSetLEDStatus\x12\x1c.zscanproto.LEDStatusRequest\x1a\x12.zscanproto.Status\x121\n" +
	"\x06GetLED\x12\x11.zscanproto.Empty\x1a\x14.zscanproto.LEDStateB\x1cZ\x1a./internal/pkg/zscanproto/b\x06proto3"

var (
	file_ZScanProto_proto_rawDescOnce sync.Once
	file_ZScanProto_proto_rawDescData []byte
)

func file_ZScanProto_proto_rawDescGZIP() []byte {
	file_ZScanProto_proto_rawDescOnce.Do(func() {
		file_ZScanProto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ZScanProto_proto_rawDesc), len(file_ZScanProto_proto_rawDesc)))
	})
	return file_ZScanProto_proto_rawDescData
}

var file_ZScanProto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ZScanProto_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ZScanProto_proto_goTypes = []any{
	(LEDStatus)(0),           // 0: zscanproto.LEDStatus
	(*Empty)(nil),            // 1: zscanproto.Empty
	(*Status)(nil),           // 2: zscanproto.Status
	(*LEDStatusRequest)(nil), // 3: zscanproto.LEDStatusRequest
	(*LEDState)(nil),         // 4: zscanproto.LEDState
}
var file_ZScanProto_proto_depIdxs = []int32{
	0, // 0: zscanproto.LEDStatusRequest.status:type_name -> zscanproto.LEDStatus
	3, // 1: zscanproto.ZPiController.SetLEDStatus:input_type -> zscanproto.LEDStatusRequest
	1, // 2: zscanproto.ZPiController.GetLED:input_type -> zscanproto.Empty
	2, // 3: zscanproto.ZPiController.SetLEDStatus:output_type -> zscanproto.Status
	4, // 4: zscanproto.ZPiController.GetLED:output_type -> zscanproto.LEDState
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ZScanProto_proto_init() }
func file_ZScanProto_proto_init() {
	if File_ZScanProto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ZScanProto_proto_rawDesc), len(file_ZScanProto_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ZScanProto_proto_goTypes,
		DependencyIndexes: file_ZScanProto_proto_depIdxs,
		EnumInfos:         file_ZScanProto_proto_enumTypes,
		MessageInfos:      file_ZScanProto_proto_msgTypes,
	}.Build()
	File_ZScanProto_proto = out.File
	file_ZScanProto_proto_goTypes = nil
	file_ZScanProto_proto_depIdxs = nil
}
