// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ZScanProto.proto

package zscanproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LEDStatus int32

const (
	LEDStatus_VOID    LEDStatus = 0
	LEDStatus_SUCCESS LEDStatus = 1
	LEDStatus_PENDING LEDStatus = 2
	LEDStatus_FAILED  LEDStatus = 3
)

// Enum value maps for LEDStatus.
var (
	LEDStatus_name = map[int32]string{
		0: "VOID",
		1: "SUCCESS",
		2: "PENDING",
		3: "FAILED",
	}
	LEDStatus_value = map[string]int32{
		"VOID":    0,
		"SUCCESS": 1,
		"PENDING": 2,
		"FAILED":  3,
	}
)

func (x LEDStatus) Enum() *LEDStatus {
	p := new(LEDStatus)
	*p = x
	return p
}

func (x LEDStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LEDStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ZScanProto_proto_enumTypes[0].Descriptor()
}

func (LEDStatus) Type() protoreflect.EnumType {
	return &file_ZScanProto_proto_enumTypes[0]
}

func (x LEDStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LEDStatus.Descriptor instead.
func (LEDStatus) EnumDescriptor() ([]byte, []int) {
	return file_ZScanProto_proto_rawDescGZIP(), []int{0}
}

type ToFState int32

const (
	ToFState_ToFDisabled ToFState = 0
	ToFState_ToFEnabled  ToFState = 1
	ToFState_ToFInactive ToFState = 2
	ToFState_ToFActive   ToFState = 3
)

// Enum value maps for ToFState.
var (
	ToFState_name = map[int32]string{
		0: "ToFDisabled",
		1: "ToFEnabled",
		2: "ToFInactive",
		3: "ToFActive",
	}
	ToFState_value = map[string]int32{
		"ToFDisabled": 0,
		"ToFEnabled":  1,
		"ToFInactive": 2,
		"ToFActive":   3,
	}
)

func (x ToFState) Enum() *ToFState {
	p := new(ToFState)
	*p = x
	return p
}

func (x ToFState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToFState) Descriptor() protoreflect.EnumDescriptor {
	return file_ZScanProto_proto_enumTypes[1].Descriptor()
}

func (ToFState) Type() protoreflect.EnumType {
	return &file_ZScanProto_proto_enumTypes[1]
}

func (x ToFState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToFState.Descriptor instead.
func (ToFState) EnumDescriptor() ([]byte, []int) {
	return file_ZScanProto_proto_rawDescGZIP(), []int{1}
}

type CamState int32

const (
	CamState_CAMREADY    CamState = 0
	CamState_CAMACTIVE   CamState = 1
	CamState_CAMINACTIVE CamState = 2
	CamState_CAMDISABLED CamState = 3
)

// Enum value maps for CamState.
var (
	CamState_name = map[int32]string{
		0: "CAMREADY",
		1: "CAMACTIVE",
		2: "CAMINACTIVE",
		3: "CAMDISABLED",
	}
	CamState_value = map[string]int32{
		"CAMREADY":    0,
		"CAMACTIVE":   1,
		"CAMINACTIVE": 2,
		"CAMDISABLED": 3,
	}
)

func (x CamState) Enum() *CamState {
	p := new(CamState)
	*p = x
	return p
}

func (x CamState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CamState) Descriptor() protoreflect.EnumDescriptor {
	return file_ZScanProto_proto_enumTypes[2].Descriptor()
}

func (CamState) Type() protoreflect.EnumType {
	return &file_ZScanProto_proto_enumTypes[2]
}

func (x CamState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CamState.Descriptor instead.
func (CamState) EnumDescriptor() ([]byte, []int) {
	return file_ZScanProto_proto_rawDescGZIP(), []int{2}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_ZScanProto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_ZScanProto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_ZScanProto_proto_rawDescGZIP(), []int{0}
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_ZScanProto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_ZScanProto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_ZScanProto_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LEDStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        LEDStatus              `protobuf:"varint,1,opt,name=status,proto3,enum=zscanproto.LEDStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LEDStatusRequest) Reset() {
	*x = LEDStatusRequest{}
	mi := &file_ZScanProto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LEDStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LEDStatusRequest) ProtoMessage() {}

func (x *LEDStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ZScanProto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LEDStatusRequest.ProtoReflect.Descriptor instead.
func (*LEDStatusRequest) Descriptor() ([]byte, []int) {
	return file_ZScanProto_proto_rawDescGZIP(), []int{2}
}

func (x *LEDStatusRequest) GetStatus() LEDStatus {
	if x != nil {
		return x.Status
	}
	return LEDStatus_VOID
}

type LEDState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Red           uint32                 `protobuf:"varint,1,opt,name=red,proto3" json:"red,omitempty"`
	Green         uint32                 `protobuf:"varint,2,opt,name=green,proto3" json:"green,omitempty"`
	Blue          uint32                 `protobuf:"varint,3,opt,name=blue,proto3" json:"blue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LEDState) Reset() {
	*x = LEDState{}
	mi := &file_ZScanProto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LEDState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LEDState) ProtoMessage() {}

func (x *LEDState) ProtoReflect() protoreflect.Message {
	mi := &file_ZScanProto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LEDState.ProtoReflect.Descriptor instead.
func (*LEDState) Descriptor() ([]byte, []int) {
	return file_ZScanProto_proto_rawDescGZIP(), []int{3}
}

func (x *LEDState) GetRed() uint32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *LEDState) GetGreen() uint32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *LEDState) GetBlue() uint32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

type ToFConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threshold     uint32                 `protobuf:"varint,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToFConfig) Reset() {
	*x = ToFConfig{}
	mi := &file_ZScanProto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToFConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToFConfig) ProtoMessage() {}

func (x *ToFConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ZScanProto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToFConfig.ProtoReflect.Descriptor instead.
func (*ToFConfig) Descriptor() ([]byte, []int) {
	return file_ZScanProto_proto_rawDescGZIP(), []int{4}
}

func (x *ToFConfig) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type CameraStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         CamState               `protobuf:"varint,1,opt,name=state,proto3,enum=zscanproto.CamState" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraStatus) Reset() {
	*x = CameraStatus{}
	mi := &file_ZScanProto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraStatus) ProtoMessage() {}

func (x *CameraStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ZScanProto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraStatus.ProtoReflect.Descriptor instead.
func (*CameraStatus) Descriptor() ([]byte, []int) {
	return file_ZScanProto_proto_rawDescGZIP(), []int{5}
}

func (x *CameraStatus) GetState() CamState {
	if x != nil {
		return x.State
	}
	return CamState_CAMREADY
}

func (x *CameraStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CameraConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Fps           uint32                 `protobuf:"varint,3,opt,name=fps,proto3" json:"fps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraConfig) Reset() {
	*x = CameraConfig{}
	mi := &file_ZScanProto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraConfig) ProtoMessage() {}

func (x *CameraConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ZScanProto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraConfig.ProtoReflect.Descriptor instead.
func (*CameraConfig) Descriptor() ([]byte, []int) {
	return file_ZScanProto_proto_rawDescGZIP(), []int{6}
}

func (x *CameraConfig) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CameraConfig) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CameraConfig) GetFps() uint32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

var File_ZScanProto_proto protoreflect.FileDescriptor

const file_ZScanProto_proto_rawDesc = "" +
	"\n" +
	"\x10ZScanProto.proto\x12\n" +
	"zscanproto\"\a\n" +
	"\x05Empty\"<\n" +
	"\x06Status\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\x10LEDStatusRequest\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.zscanproto.LEDStatusR\x06status\"F\n" +
	"\bLEDState\x12\x10\n" +
	"\x03red\x18\x01 \x01(\rR\x03red\x12\x14\n" +
	"\x05green\x18\x02 \x01(\rR\x05green\x12\x12\n" +
	"\x04blue\x18\x03 \x01(\rR\x04blue\")\n" +
	"\tToFConfig\x12\x1c\n" +
	"\tthreshold\x18\x01 \x01(\rR\tthreshold\"T\n" +
	"\fCameraStatus\x12*\n" +
	"\x05state\x18\x01 \x01(\x0e2\x14.zscanproto.CamStateR\x05state\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\fCameraConfig\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\x12\x10\n" +
	"\x03fps\x18\x03 \x01(\rR\x03fps*;\n" +
	"\tLEDStatus\x12\b\n" +
	"\x04VOID\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\v\n" +
	"\aPENDING\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03*K\n" +
	"\bToFState\x12\x0f\n" +
	"\vToFDisabled\x10\x00\x12\x0e\n" +
	"\n" +
	"ToFEnabled\x10\x01\x12\x0f\n" +
	"\vToFInactive\x10\x02\x12\r\n" +
	"\tToFActive\x10\x03*I\n" +
	"\bCamState\x12\f\n" +
	"\bCAMREADY\x10\x00\x12\r\n" +
	"\tCAMACTIVE\x10\x01\x12\x0f\n" +
	"\vCAMINACTIVE\x10\x02\x12\x0f\n" +
	"\vCAMDISABLED\x10\x032\xcb\x04\n" +
	"\rZPiController\x12@\n" +
	"\fSetLEDStatus\x12\x1c.zscanproto.LEDStatusRequest\x1a\x12.zscanproto.Status\x121\n" +
	"\x06GetLED\x12\x11.zscanproto.Empty\x1a\x14.zscanproto.LEDState\x129\n" +
	"\fConfigureToF\x12\x15.zscanproto.ToFConfig\x1a\x12.zscanproto.Status\x122\n" +
	"\tEnableToF\x12\x11.zscanproto.Empty\x1a\x12.zscanproto.Status\x123\n" +
	"\n" +
	"DisableToF\x12\x11.zscanproto.Empty\x1a\x12.zscanproto.Status\x124\n" +
	"\vActivateToF\x12\x11.zscanproto.Empty\x1a\x12.zscanproto.Status\x126\n" +
	"\rDeactivateToF\x12\x11.zscanproto.Empty\x1a\x12.zscanproto.Status\x127\n" +
	"\x0eActivateCamera\x12\x11.zscanproto.Empty\x1a\x12.zscanproto.Status\x129\n" +
	"\x10DeactivateCamera\x12\x11.zscanproto.Empty\x1a\x12.zscanproto.Status\x12?\n" +
	"\x0fConfigureCamera\x12\x18.zscanproto.CameraConfig\x1a\x12.zscanproto.StatusB\x1cZ\x1a./internal/pkg/zscanproto/b\x06proto3"

var (
	file_ZScanProto_proto_rawDescOnce sync.Once
	file_ZScanProto_proto_rawDescData []byte
)

func file_ZScanProto_proto_rawDescGZIP() []byte {
	file_ZScanProto_proto_rawDescOnce.Do(func() {
		file_ZScanProto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ZScanProto_proto_rawDesc), len(file_ZScanProto_proto_rawDesc)))
	})
	return file_ZScanProto_proto_rawDescData
}

var file_ZScanProto_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_ZScanProto_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ZScanProto_proto_goTypes = []any{
	(LEDStatus)(0),           // 0: zscanproto.LEDStatus
	(ToFState)(0),            // 1: zscanproto.ToFState
	(CamState)(0),            // 2: zscanproto.CamState
	(*Empty)(nil),            // 3: zscanproto.Empty
	(*Status)(nil),           // 4: zscanproto.Status
	(*LEDStatusRequest)(nil), // 5: zscanproto.LEDStatusRequest
	(*LEDState)(nil),         // 6: zscanproto.LEDState
	(*ToFConfig)(nil),        // 7: zscanproto.ToFConfig
	(*CameraStatus)(nil),     // 8: zscanproto.CameraStatus
	(*CameraConfig)(nil),     // 9: zscanproto.CameraConfig
}
var file_ZScanProto_proto_depIdxs = []int32{
	0,  // 0: zscanproto.LEDStatusRequest.status:type_name -> zscanproto.LEDStatus
	2,  // 1: zscanproto.CameraStatus.state:type_name -> zscanproto.CamState
	5,  // 2: zscanproto.ZPiController.SetLEDStatus:input_type -> zscanproto.LEDStatusRequest
	3,  // 3: zscanproto.ZPiController.GetLED:input_type -> zscanproto.Empty
	7,  // 4: zscanproto.ZPiController.ConfigureToF:input_type -> zscanproto.ToFConfig
	3,  // 5: zscanproto.ZPiController.EnableToF:input_type -> zscanproto.Empty
	3,  // 6: zscanproto.ZPiController.DisableToF:input_type -> zscanproto.Empty
	3,  // 7: zscanproto.ZPiController.ActivateToF:input_type -> zscanproto.Empty
	3,  // 8: zscanproto.ZPiController.DeactivateToF:input_type -> zscanproto.Empty
	3,  // 9: zscanproto.ZPiController.ActivateCamera:input_type -> zscanproto.Empty
	3,  // 10: zscanproto.ZPiController.DeactivateCamera:input_type -> zscanproto.Empty
	9,  // 11: zscanproto.ZPiController.ConfigureCamera:input_type -> zscanproto.CameraConfig
	4,  // 12: zscanproto.ZPiController.SetLEDStatus:output_type -> zscanproto.Status
	6,  // 13: zscanproto.ZPiController.GetLED:output_type -> zscanproto.LEDState
	4,  // 14: zscanproto.ZPiController.ConfigureToF:output_type -> zscanproto.Status
	4,  // 15: zscanproto.ZPiController.EnableToF:output_type -> zscanproto.Status
	4,  // 16: zscanproto.ZPiController.DisableToF:output_type -> zscanproto.Status
	4,  // 17: zscanproto.ZPiController.ActivateToF:output_type -> zscanproto.Status
	4,  // 18: zscanproto.ZPiController.DeactivateToF:output_type -> zscanproto.Status
	4,  // 19: zscanproto.ZPiController.ActivateCamera:output_type -> zscanproto.Status
	4,  // 20: zscanproto.ZPiController.DeactivateCamera:output_type -> zscanproto.Status
	4,  // 21: zscanproto.ZPiController.ConfigureCamera:output_type -> zscanproto.Status
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_ZScanProto_proto_init() }
func file_ZScanProto_proto_init() {
	if File_ZScanProto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ZScanProto_proto_rawDesc), len(file_ZScanProto_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ZScanProto_proto_goTypes,
		DependencyIndexes: file_ZScanProto_proto_depIdxs,
		EnumInfos:         file_ZScanProto_proto_enumTypes,
		MessageInfos:      file_ZScanProto_proto_msgTypes,
	}.Build()
	File_ZScanProto_proto = out.File
	file_ZScanProto_proto_goTypes = nil
	file_ZScanProto_proto_depIdxs = nil
}
