// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ZScanProto.proto

package zproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_ZScanProto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_ZScanProto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_ZScanProto_proto_rawDescGZIP(), []int{0}
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_ZScanProto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_ZScanProto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_ZScanProto_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LEDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Red           uint32                 `protobuf:"varint,1,opt,name=red,proto3" json:"red,omitempty"`
	Green         uint32                 `protobuf:"varint,2,opt,name=green,proto3" json:"green,omitempty"`
	Blue          uint32                 `protobuf:"varint,3,opt,name=blue,proto3" json:"blue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LEDRequest) Reset() {
	*x = LEDRequest{}
	mi := &file_ZScanProto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LEDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LEDRequest) ProtoMessage() {}

func (x *LEDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ZScanProto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LEDRequest.ProtoReflect.Descriptor instead.
func (*LEDRequest) Descriptor() ([]byte, []int) {
	return file_ZScanProto_proto_rawDescGZIP(), []int{2}
}

func (x *LEDRequest) GetRed() uint32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *LEDRequest) GetGreen() uint32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *LEDRequest) GetBlue() uint32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

type LEDState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Red           uint32                 `protobuf:"varint,1,opt,name=red,proto3" json:"red,omitempty"`
	Green         uint32                 `protobuf:"varint,2,opt,name=green,proto3" json:"green,omitempty"`
	Blue          uint32                 `protobuf:"varint,3,opt,name=blue,proto3" json:"blue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LEDState) Reset() {
	*x = LEDState{}
	mi := &file_ZScanProto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LEDState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LEDState) ProtoMessage() {}

func (x *LEDState) ProtoReflect() protoreflect.Message {
	mi := &file_ZScanProto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LEDState.ProtoReflect.Descriptor instead.
func (*LEDState) Descriptor() ([]byte, []int) {
	return file_ZScanProto_proto_rawDescGZIP(), []int{3}
}

func (x *LEDState) GetRed() uint32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *LEDState) GetGreen() uint32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *LEDState) GetBlue() uint32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

var File_ZScanProto_proto protoreflect.FileDescriptor

const file_ZScanProto_proto_rawDesc = "" +
	"\n" +
	"\x10ZScanProto.proto\x12\n" +
	"ZScanProto\"\a\n" +
	"\x05Empty\"<\n" +
	"\x06Status\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\n" +
	"LEDRequest\x12\x10\n" +
	"\x03red\x18\x01 \x01(\rR\x03red\x12\x14\n" +
	"\x05green\x18\x02 \x01(\rR\x05green\x12\x12\n" +
	"\x04blue\x18\x03 \x01(\rR\x04blue\"F\n" +
	"\bLEDState\x12\x10\n" +
	"\x03red\x18\x01 \x01(\rR\x03red\x12\x14\n" +
	"\x05green\x18\x02 \x01(\rR\x05green\x12\x12\n" +
	"\x04blue\x18\x03 \x01(\rR\x04blue2x\n" +
	"\rZPiController\x124\n" +
	"\x06SetLED\x12\x16.ZScanProto.LEDRequest\x1a\x12.ZScanProto.Status\x121\n" +
	"\x06GetLED\x12\x11.ZScanProto.Empty\x1a\x14.ZScanProto.LEDStateB\x14Z\x12./api/grpc/zproto/b\x06proto3"

var (
	file_ZScanProto_proto_rawDescOnce sync.Once
	file_ZScanProto_proto_rawDescData []byte
)

func file_ZScanProto_proto_rawDescGZIP() []byte {
	file_ZScanProto_proto_rawDescOnce.Do(func() {
		file_ZScanProto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ZScanProto_proto_rawDesc), len(file_ZScanProto_proto_rawDesc)))
	})
	return file_ZScanProto_proto_rawDescData
}

var file_ZScanProto_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ZScanProto_proto_goTypes = []any{
	(*Empty)(nil),      // 0: ZScanProto.Empty
	(*Status)(nil),     // 1: ZScanProto.Status
	(*LEDRequest)(nil), // 2: ZScanProto.LEDRequest
	(*LEDState)(nil),   // 3: ZScanProto.LEDState
}
var file_ZScanProto_proto_depIdxs = []int32{
	2, // 0: ZScanProto.ZPiController.SetLED:input_type -> ZScanProto.LEDRequest
	0, // 1: ZScanProto.ZPiController.GetLED:input_type -> ZScanProto.Empty
	1, // 2: ZScanProto.ZPiController.SetLED:output_type -> ZScanProto.Status
	3, // 3: ZScanProto.ZPiController.GetLED:output_type -> ZScanProto.LEDState
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ZScanProto_proto_init() }
func file_ZScanProto_proto_init() {
	if File_ZScanProto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ZScanProto_proto_rawDesc), len(file_ZScanProto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ZScanProto_proto_goTypes,
		DependencyIndexes: file_ZScanProto_proto_depIdxs,
		MessageInfos:      file_ZScanProto_proto_msgTypes,
	}.Build()
	File_ZScanProto_proto = out.File
	file_ZScanProto_proto_goTypes = nil
	file_ZScanProto_proto_depIdxs = nil
}
