// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: ZScanProto.proto

package zproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZPiController_SetLED_FullMethodName = "/ZScanProto.ZPiController/SetLED"
	ZPiController_GetLED_FullMethodName = "/ZScanProto.ZPiController/GetLED"
)

// ZPiControllerClient is the client API for ZPiController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZPiControllerClient interface {
	SetLED(ctx context.Context, in *LEDRequest, opts ...grpc.CallOption) (*Status, error)
	GetLED(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LEDState, error)
}

type zPiControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewZPiControllerClient(cc grpc.ClientConnInterface) ZPiControllerClient {
	return &zPiControllerClient{cc}
}

func (c *zPiControllerClient) SetLED(ctx context.Context, in *LEDRequest, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, ZPiController_SetLED_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zPiControllerClient) GetLED(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LEDState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LEDState)
	err := c.cc.Invoke(ctx, ZPiController_GetLED_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZPiControllerServer is the server API for ZPiController service.
// All implementations must embed UnimplementedZPiControllerServer
// for forward compatibility.
type ZPiControllerServer interface {
	SetLED(context.Context, *LEDRequest) (*Status, error)
	GetLED(context.Context, *Empty) (*LEDState, error)
	mustEmbedUnimplementedZPiControllerServer()
}

// UnimplementedZPiControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZPiControllerServer struct{}

func (UnimplementedZPiControllerServer) SetLED(context.Context, *LEDRequest) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLED not implemented")
}
func (UnimplementedZPiControllerServer) GetLED(context.Context, *Empty) (*LEDState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLED not implemented")
}
func (UnimplementedZPiControllerServer) mustEmbedUnimplementedZPiControllerServer() {}
func (UnimplementedZPiControllerServer) testEmbeddedByValue()                       {}

// UnsafeZPiControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZPiControllerServer will
// result in compilation errors.
type UnsafeZPiControllerServer interface {
	mustEmbedUnimplementedZPiControllerServer()
}

func RegisterZPiControllerServer(s grpc.ServiceRegistrar, srv ZPiControllerServer) {
	// If the following call panics, it indicates UnimplementedZPiControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZPiController_ServiceDesc, srv)
}

func _ZPiController_SetLED_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LEDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZPiControllerServer).SetLED(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZPiController_SetLED_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZPiControllerServer).SetLED(ctx, req.(*LEDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZPiController_GetLED_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZPiControllerServer).GetLED(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZPiController_GetLED_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZPiControllerServer).GetLED(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ZPiController_ServiceDesc is the grpc.ServiceDesc for ZPiController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZPiController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ZScanProto.ZPiController",
	HandlerType: (*ZPiControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetLED",
			Handler:    _ZPiController_SetLED_Handler,
		},
		{
			MethodName: "GetLED",
			Handler:    _ZPiController_GetLED_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ZScanProto.proto",
}
